name: Run Smoke Tests

on:
  workflow_run:
    workflows:
      - "trigger"
    types:
      - completed

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
          echo "Hello "
